### ISSUE TITLE
I stop seeing the mouse after a while

### ISSUE THREAD

**Issue by ghost** [AG7GN/dwservice#1]
Hello. I have linux and firefox. I connect to a client and after a while i stop seeing the mouse, only the shadow or the hover selection, but not the mouse. Any ideia what is causing this?

**Comment by AG7GN** [comment]
This is not the official repository for dwservice. It only contains information about how to configure dwservice for certain scenarios. I suggest you post your question to dwservice team at https://www.dwservice.net/en/contactus.html?_request=main&page=contactus.

**Comment by ghost** [comment]
ok thank you
