### ISSUE TITLE
Improved Linux instructions for running as a regular user

### ISSUE THREAD

**Issue by ligius-** [AG7GN/dwservice#3]
For reference: https://github.com/AG7GN/dwservice/blob/master/README.md#optional-run-the-dwagent-as-a-regular-user-on-linux

The editing of the file can be replaced with a single line:
```
sed -i 's/WantedBy=multi-user.target/WantedBy=default.target/' dwagent.service
```

The chown command for the folder needs to be run recursively:
```
sudo chown -R bob:bob /usr/share/dwagent/
```

**Comment by AG7GN** [comment]
Updated. Thank you!
