### ISSUE TITLE
Start of agent from ssh session

### ISSUE THREAD

**Issue by fleutot** [AG7GN/dwservice#4]
I want to start the agent (on a Mac) from an ssh session.
This is what I have tried:

```
sudo /Library/DWAgent/native/dwagsvc start
```
The agent starts, and I can login through the web interface, add files from  the text editor, the web terminal works... but I cannot open a Screen. There is nothing to choose form in the Desktop selection.

My guess is that only the Desktop from which the agent was started, can be accessed through the web service.

Is there any way I can grab the current local desktop, after starting the agent itself from elsewhere? I tried starting it without sudo, and as the same user who's logged in in the current GUI session, to no av.

**Comment by AG7GN** [comment]
This is not the official repository for DWService. It only contains my personal notes about how to configure dwservice for certain scenarios. I recommend that you [post your question to the DWService team](https://www.dwservice.net/en/contactus.html?_request=main&page=contactus).
